# Generated by Django 4.0.1 on 2022-02-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='staffdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('staff_details', models.CharField(default='', max_length=200)),
                ('Date_of_Birth', models.DateField(default='2000-12-31')),
                ('Designation', models.CharField(default='', max_length=100)),
                ('Eductaion', models.CharField(default='', max_length=300)),
                ('Subject_of_Teaching', models.CharField(default='', max_length=100)),
                ('Teaching_Experience', models.CharField(default='', max_length=100)),
                ('review', models.CharField(default='', max_length=300)),
                ('image', models.ImageField(default='', upload_to='staff/images')),
            ],
        ),
    ]
