# Generated by Django 4.0.1 on 2022-02-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_staffdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('blog_details', models.CharField(default='', max_length=200)),
                ('Type', models.CharField(default='', max_length=30)),
                ('date', models.DateField(default='2000-12-31')),
            ],
        ),
    ]
