# Generated by Django 4.0.1 on 2022-03-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_newspaper_blogdetails_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='maingallery',
            name='details',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='newspaper',
            name='details',
            field=models.CharField(default='', max_length=200),
        ),
    ]
