# Generated by Django 4.0.1 on 2022-03-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_maingallery_details_newspaper_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('company_details', models.CharField(default='', max_length=200)),
                ('Type', models.CharField(default='', max_length=30)),
                ('date', models.DateField(default='2000-12-31')),
                ('image', models.ImageField(default='', upload_to='company/images')),
            ],
        ),
        migrations.AlterField(
            model_name='blogdetails',
            name='image',
            field=models.ImageField(default='', upload_to='blog/images'),
        ),
    ]
