# Generated by Django 4.0.1 on 2022-03-07 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_placement_placementdetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='placement',
            new_name='placementss',
        ),
    ]
