# Generated by Django 4.0.1 on 2022-03-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_rename_placement_placementss'),
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('motive', models.CharField(default='', max_length=100)),
                ('Type', models.CharField(default='', max_length=30)),
                ('project_details', models.CharField(default='', max_length=200)),
                ('Date_of_project', models.DateField(default='2000-12-31')),
                ('Achievements', models.CharField(default='', max_length=300)),
                ('Subject', models.CharField(default='', max_length=100)),
                ('review', models.CharField(default='', max_length=300)),
                ('image', models.ImageField(default='', upload_to='projects/images')),
            ],
        ),
        migrations.CreateModel(
            name='projectsdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_projects', models.CharField(default='', max_length=30)),
                ('Bestproject', models.CharField(default='', max_length=30)),
                ('numberofprojectcoordinated', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='placementss',
            old_name='Eductaion',
            new_name='Education',
        ),
    ]
