# Generated by Django 4.0.1 on 2022-03-07 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_projects_projectsdetails_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='projects',
            new_name='projectss',
        ),
    ]
