# Generated by Django 4.0.1 on 2022-03-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_rename_projects_projectss'),
    ]

    operations = [
        migrations.CreateModel(
            name='trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(default='', max_length=30)),
                ('place', models.CharField(default='', max_length=30)),
                ('date', models.DateField(default='2000-12-31')),
                ('details', models.CharField(default='', max_length=200)),
                ('image', models.ImageField(default='', upload_to='gallery/images')),
                ('image1', models.ImageField(default='', upload_to='gallery/images')),
                ('image2', models.ImageField(default='', upload_to='gallery/images')),
                ('image3', models.ImageField(default='', upload_to='gallery/images')),
            ],
        ),
    ]
