# Generated by Django 4.0.1 on 2022-03-07 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_trip'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='trip',
            new_name='trips',
        ),
    ]
