# Generated by Django 4.0.1 on 2022-03-07 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_rename_trip_trips'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='trips',
            new_name='tripss',
        ),
    ]
