# Generated by Django 4.0.1 on 2022-03-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_blogdetails_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetails',
            name='blog_details',
            field=models.CharField(default='', max_length=20000),
        ),
    ]
