# Generated by Django 4.0.1 on 2022-03-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_alter_blogdetails_blog_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogdetails',
            name='blog_details',
        ),
        migrations.AddField(
            model_name='blogdetails',
            name='blog_details1',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='blogdetails',
            name='blog_details2',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
