# Generated by Django 4.0.1 on 2022-03-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_remove_blogdetails_blog_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tripsdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_trips', models.CharField(default='', max_length=30)),
                ('Besttrip', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
