# Generated by Django 4.0.1 on 2022-03-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_tripsdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_staff', models.CharField(default='', max_length=30)),
                ('total_departments', models.CharField(default='', max_length=30)),
                ('totalnontechingstaff', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
