# Generated by Django 4.0.1 on 2022-03-13 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_staff'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='staff',
            new_name='staffs',
        ),
    ]
