# Generated by Django 4.0.1 on 2022-03-13 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_rename_staff_staffs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffdetails',
            old_name='Date_of_Birth',
            new_name='Date_of_joining',
        ),
    ]
