# Generated by Django 4.0.1 on 2022-03-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_patent'),
    ]

    operations = [
        migrations.AddField(
            model_name='patent',
            name='patentnumber',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='patent',
            name='year',
            field=models.CharField(default='', max_length=100),
        ),
    ]
