# Generated by Django 4.0.1 on 2022-03-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0031_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='link',
        ),
        migrations.AddField(
            model_name='course',
            name='coursetype',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='details',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='modeofstudy',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='programecode',
            field=models.CharField(default='', max_length=50),
        ),
    ]
