# Generated by Django 4.0.1 on 2022-03-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0032_remove_course_link_course_coursetype_course_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='shorttitle',
            field=models.CharField(default='', max_length=100),
        ),
    ]
