# Generated by Django 4.0.1 on 2022-03-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0033_course_shorttitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='details',
            field=models.CharField(default='', max_length=4000),
        ),
    ]
