# Generated by Django 4.0.1 on 2022-03-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0034_alter_course_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='dergree',
            field=models.CharField(default='', max_length=100),
        ),
    ]
