# Generated by Django 4.0.1 on 2022-03-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0035_course_dergree'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectss',
            name='image1',
            field=models.ImageField(default='', upload_to='projects/images'),
        ),
        migrations.AddField(
            model_name='projectss',
            name='image2',
            field=models.ImageField(default='', upload_to='projects/images'),
        ),
        migrations.AddField(
            model_name='projectss',
            name='image3',
            field=models.ImageField(default='', upload_to='projects/images'),
        ),
    ]
