# Generated by Django 4.0.1 on 2022-03-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0036_projectss_image1_projectss_image2_projectss_image3'),
    ]

    operations = [
        migrations.AddField(
            model_name='cutoff',
            name='year',
            field=models.CharField(default='', max_length=100),
        ),
    ]
