# Generated by Django 4.0.1 on 2022-03-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0037_cutoff_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripss',
            name='image',
            field=models.ImageField(default='', upload_to='trip/images'),
        ),
        migrations.AlterField(
            model_name='tripss',
            name='image1',
            field=models.ImageField(default='', upload_to='trip/images'),
        ),
        migrations.AlterField(
            model_name='tripss',
            name='image2',
            field=models.ImageField(default='', upload_to='trip/images'),
        ),
        migrations.AlterField(
            model_name='tripss',
            name='image3',
            field=models.ImageField(default='', upload_to='trip/images'),
        ),
    ]
