# Generated by Django 4.0.1 on 2022-03-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0038_alter_tripss_image_alter_tripss_image1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('link', models.CharField(default='', max_length=500)),
                ('year', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='tripss',
            name='details',
            field=models.CharField(default='', max_length=700),
        ),
    ]
