# Generated by Django 4.0.1 on 2022-03-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0039_publication_alter_tripss_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='', max_length=30)),
                ('data', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
