# Generated by Django 4.0.1 on 2022-03-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0040_chart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chart',
            old_name='data',
            new_name='Averagepackage',
        ),
        migrations.RenameField(
            model_name='chart',
            old_name='label',
            new_name='Highestpackage',
        ),
        migrations.AddField(
            model_name='chart',
            name='Companiesrecruiting',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='chart',
            name='studentselected',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='chart',
            name='studentselectedinbranch_Aiml',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='chart',
            name='studentselectedinbranch_Auto',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='chart',
            name='studentselectedinbranch_Civil',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='chart',
            name='studentselectedinbranch_Data',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='chart',
            name='studentselectedinbranch_Electronics',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='chart',
            name='studentselectedinbranch_Electronicsandtele',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='chart',
            name='studentselectedinbranch_IT',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='chart',
            name='studentselectedinbranch_Mech',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='chart',
            name='studentselectedinbranch_comp',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='chart',
            name='studentselectedinbranch_humanities',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='chart',
            name='year',
            field=models.CharField(default='', max_length=30),
        ),
    ]
