# Generated by Django 4.0.1 on 2022-03-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0042_messagebox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagebox',
            name='date',
            field=models.DateField(default='03-31'),
        ),
    ]
