# Generated by Django 4.0.1 on 2022-03-31 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0045_apply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apply',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='apply',
            old_name='Contactnumber',
            new_name='contactnumber',
        ),
        migrations.RenameField(
            model_name='apply',
            old_name='Firstname',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='apply',
            old_name='Lastname',
            new_name='lastname',
        ),
    ]
