# Generated by Django 4.0.1 on 2022-03-31 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0046_rename_city_apply_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='id',
        ),
        migrations.AddField(
            model_name='apply',
            name='apply_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apply',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='apply',
            name='contactnumber',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='apply',
            name='course',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='apply',
            name='firstname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='apply',
            name='lastname',
            field=models.CharField(max_length=100),
        ),
    ]
