# Generated by Django 4.0.1 on 2022-03-31 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0048_apply_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='date',
            field=models.CharField(default='', max_length=100),
        ),
    ]
