# Generated by Django 4.0.1 on 2022-04-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0049_alter_apply_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='achievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='2000-12-31')),
                ('eventname', models.CharField(default='', max_length=30)),
                ('details', models.CharField(default='', max_length=200)),
                ('image', models.ImageField(default='', upload_to='gallery/images')),
            ],
        ),
    ]
