# Generated by Django 4.0.1 on 2022-01-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce', '0002_product_category_product_image_product_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=50)),
                ('zipcode', models.IntegerField(default=0)),
                ('phonenumber', models.IntegerField(default=0)),
                ('city', models.CharField(default='', max_length=100)),
                ('state', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
