# Generated by Django 4.0.1 on 2022-01-23 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce', '0003_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phonenumber',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='zipcode',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
