# Generated by Django 4.0.1 on 2022-01-23 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce', '0004_alter_order_phonenumber_alter_order_zipcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='phonenumber',
            new_name='Zip',
        ),
        migrations.RemoveField(
            model_name='order',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
