# Generated by Django 4.0.1 on 2022-01-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce', '0005_rename_phonenumber_order_zip_remove_order_zipcode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Zip',
        ),
        migrations.AddField(
            model_name='order',
            name='Zipcode',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
