# Generated by Django 4.0.1 on 2022-01-23 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce', '0007_remove_order_zipcode_remove_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Zipcode',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='', max_length=100),
        ),
    ]
