from django.contrib import admin
from .models import maingallery,staffdetails,blogdetails,newspaper,company,placementss,placementdetails,projectss,projectsdetails,tripss,tripsdetails,staffs,patent,alumini,calender,cutoff,syllabus,question,firstyearquestion,placementstestquestion,conference,course,publication,chart,messagebox,admissionform,Apply
admin.site.register(maingallery)
admin.site.register(messagebox)
admin.site.register(Apply)
admin.site.register(chart)

admin.site.register(syllabus)
admin.site.register(course)
admin.site.register(question)
admin.site.register(admissionform)
admin.site.register(firstyearquestion)
admin.site.register(placementstestquestion)
admin.site.register(conference)
admin.site.register(patent)
admin.site.register(calender)
admin.site.register(cutoff)
admin.site.register(blogdetails)
admin.site.register(staffdetails)
admin.site.register(staffs)
admin.site.register(alumini)
admin.site.register(newspaper)
admin.site.register(company)
admin.site.register(placementss)
admin.site.register(publication)
admin.site.register(placementdetails)
admin.site.register(projectss)
admin.site.register(projectsdetails)
admin.site.register(tripss)
admin.site.register(tripsdetails)
# Register your models here.
