from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('',views.index,name='index'),
    path('about/' ,views.about,name='aboutus'),
    path('masters/' ,views.masters,name='masters'),
    path('elearning/' ,views.elearning,name='elearning'),
    path('secretary/' ,views.secretary,name='secretary'),
    path('principal/' ,views.principal,name='principal'),
    path('chairman/' ,views.chairman,name='chairman'),
    path('bachlers/' ,views.bachlers,name='bachlers'),
    path('publication/' ,views.publicat,name='publication'),
    path('patent/' ,views.patents,name='patent'),
    path('mhtcetcutoff/' ,views.cutoffs,name='cutoff'),
    path('unisyllabus/' ,views.syllabuss,name='syllabus'),
    path('questions/' ,views.questions,name='questions'),
    path('procedure/' ,views.procedure,name='procedure'),
    path('aluminis/' ,views.aluminis,name='aluminis'),
    path('register/' ,views.register,name='registers'),
    path('calender/' ,views.calenders,name='calender'),
    path('overview/' ,views.libraryoverview,name='overview'),
    path('admission/' ,views.admission,name='admission'),
    path('apply/' ,views.apply,name='apply'),
    path('basic/' ,views.basic,name='basic'),
    path('blog/' ,views.blog,name='blog'),
    path('companies/' ,views.companies,name='companies'),
    path('courses/' ,views.courses,name='courses'),
    path('gallery/' ,views.gallery,name='gallery'),
    path('news/' ,views.news,name='news'),
    path('placement/' ,views.placement,name='placement'),
    path('projects/' ,views.projects,name='projects'),
    path('research/' ,views.research,name='research'),
    path('sports/' ,views.sports,name='sports'),
    path('student/' ,views.student,name='student'),
    path('trips/' ,views.trips,name='trips'),
    path('staff/' ,views.staff,name='staff'),
    path('conference/' ,views.conferences,name='conference'),
    path('placementtestmaterial/' ,views.placementtestmaterial,name='placementtestmaterial'),
    path("<int:id>/", views.courses, name="ProductView"),
]